---
title: "pdo_tissue_clustering"
output: html_document
date: "2023-09-11"
---

```{r}
library(tidyr)
library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
library(maftools)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
res_path <- "../results/combined_batches_wes/"
```

```{r}
jaccard_dist = function(x, y) {
	s = 1 - sum(x & y)/sum(x | y)
	if(is.na(s)) {
		return(1)
	} else {
		return(s)
	}
}

hamming_dist <- function(x, y) {
  if (length(x) != length(y)) {
    stop("Vectors must be of the same length!")
  }
  
  sum(x != y)
}
```

```{r}
merged_maf <-read.maf(paste0(res_path, "merged_mafs_allBatches_160124_maftools.maf"), 
                 verbose=TRUE)
# Load in metadata containing KRAS mutation information from sanger seuqencing
metadata_wes <- readxl::read_excel("../metadata/metadata_all_samples.xlsx")

# Cleaning the clinical data column to match with metadata spec
merged_maf@clinical.data <- merged_maf@clinical.data %>%
  tidyr::separate(Tumor_Sample_Barcode, into = c("Patient", "Sample", "Treatment"), sep = "_", remove=FALSE) %>%
  dplyr::mutate(Sample_Label = stringr::str_extract(Sample, "[A-Za-z]+")) %>%
  dplyr::mutate(Sample_Clean = stringr::str_replace(Sample, "RT.*", "R")) %>%
  data.table::setDT() 

# Adding in metadata info
merged_maf@clinical.data <- dplyr::left_join(merged_maf@clinical.data, metadata_wes, by=c("Sample_Clean" = "Label")) %>%
  dplyr::rename(Stage = `Stage at diagnosis...10`)
```

```{r}
# Extract metadata to add to heatmap
patients<-merged_maf@clinical.data$Patient
sample_conditions <- merged_maf@clinical.data$Treatment

# Create color palette
patients_color_palette <- colorRampPalette(brewer.pal(8, "Dark2"))(length(unique(patients)))
conditions_color_palette <- viridis::viridis(length(unique(sample_conditions)), option="D")

# Create named vector mapping prefixes to colors
patients_color_mapping <- setNames(patients_color_palette, unique(patients))
df_patients_color_mapping <- patients_color_mapping[patients]
names(df_patients_color_mapping) <- mymaf@clinical.data$Tumor_Sample_Barcode

conditions_color_mapping <- setNames(conditions_color_palette, unique(sample_conditions))
df_conditions_color_mapping <- conditions_color_mapping[sample_conditions]
names(df_conditions_color_mapping) <- mymaf@clinical.data$Tumor_Sample_Barcode

# Create a data frame for the heatmap annotation
annotation_df <- data.frame(patients = patients, conditions = sample_conditions)
rownames(annotation_df) <- mymaf@clinical.data$Tumor_Sample_Barcode
```

```{r}
data(cgc_67, package = "COSMIC.67")
cosmic_genes <- getGeneSummary(merged_maf)$Hugo_Symbol[getGeneSummary(merged_maf)$Hugo_Symbol %in% cgc_67$SYMBOL]

# Create a unique mutation identifier and include only cosmic genes
mutation_data <- merged_maf@data %>% 
  mutate(unique_mutation = paste(Hugo_Symbol, HGVSp, sep = "_")) %>%
  dplyr::filter(Hugo_Symbol %in% cosmic_genes )
  
# Pivot to create a matrix suitable for clustering
# We use the tidyr package's pivot_wider function to achieve this
mutation_matrix <- mutation_data %>%
  dplyr::select(Tumor_Sample_Barcode, unique_mutation) %>%
  dplyr::distinct() %>%
  dplyr::mutate(value = 1) %>% # Add a value column
  tidyr::pivot_wider(names_from = unique_mutation, values_from = value, values_fill = 0) # Pivot the data

heatmap_data <- t(mutation_matrix[,-1])
colnames(heatmap_data) <- mutation_matrix[, 1] %>% pull()
heatmap_data
#oncoplot(mymaf, writeMatrix=TRUE)
# Define a color mapping for mutations
col_fun <- c("0" = "black", "1" = "yellow")
```

Showing only samples with TISSUE and also in a particular order

```{r}
cm_neg_tissue_samples
base_ids <- grep(cm_neg_tissue_samples, pattern="TISSUE))", value=TRUE)
base_ids <- str_extract(colnames(heatmap_data), ".*(?=_(TISSUE))") %>% na.omit()
unique_ids <- unique(base_ids)
samples_of_interest <- c()
for (sample_id in unique_ids){
  samples_of_interest <- c(samples_of_interest, grep(colnames(heatmap_data), pattern=sample_id, value=TRUE))
}

annotation_df <- annotation_df[colnames(heatmap_data),]
annotation_df_small <- annotation_df[samples_of_interest,]
heatmap_data_small <- heatmap_data[,samples_of_interest]
```


```{r}
set.seed(2022)

ht <- Heatmap(heatmap_data, 
        name = "mutations",
        col = col_fun,
        column_dend_height = unit(50, "mm"),
        show_column_names = TRUE, # Show column names
        show_row_names = FALSE,
        cluster_rows = FALSE, # don't cluster mutations
        column_names_gp = gpar(fontsize = 10),  # reduce column names font size
        cluster_columns = TRUE, # cluster samples
        clustering_distance_columns=jaccard_dist,
        column_km=17,
        show_heatmap_legend=TRUE,
        top_annotation = HeatmapAnnotation(df = annotation_df, col = list(patients = patients_color_mapping, conditions=conditions_color_mapping)))

png(paste0(res_path,"unsupervised_clustering_snps_indels_shortName_COSMIC.png"), res=300, units = "in", width = 15, height=10)
ht
dev.off()
```

Only the 7 samples with matched tissue
```{r}
set.seed(2022)
# Create the heatmap with unsupervised clustering
ht_small <- Heatmap(heatmap_data_small, 
        name = "mutations",
        col = col_fun,
        column_dend_height = unit(50, "mm"),
        show_column_names = TRUE, # Show column names
        show_row_names = FALSE,
        cluster_rows = FALSE, # don't cluster mutations
        column_names_gp = gpar(fontsize = 10),  # reduce column names font size
        cluster_columns = TRUE, # cluster samples
        clustering_distance_columns=jaccard_dist,
        column_km=7,
        show_heatmap_legend=TRUE,
        top_annotation = HeatmapAnnotation(df = annotation_df_small, col = list(patients = patients_color_mapping, conditions=conditions_color_mapping)))

png(paste0(res_path,"unsupervised_clustering_snps_indels_shortName_COSMIC_onlyMatchedTissue.png"), res=300, units = "in", width = 15, height=10)
ht_small
dev.off()
```