---
title: "MSIsensor"
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
res_path <- "../results/combined_batches_wes/msisensorpro/"
```

```{r}
read_msisensor <- function(filepath){
  df <- read.table(filepath, header=TRUE) %>%
    dplyr::mutate(sample_name = stringr::str_extract(filepath, "[^/]+$"))
  return(df)
}
```

```{r}
files <- list.files(res_path, pattern="*_PBMC$", full.names=TRUE, recursive=TRUE)
msisensor_df <- purrr::map_dfr(files, read_msisensor) %>%
  dplyr::rename(pert = "X.") %>%
  tidyr::separate(sample_name, into = c("Patient", "Sample", "a", "b", "c"), sep = "_", remove=FALSE) %>%
   dplyr::mutate(Patient = stringr::str_replace(Patient, "63RT3", "63RT"),
                 Patient = stringr::str_replace(Patient, "RT", "R"),
                 Patient = paste0("PCA", Patient))

msi_colors <- ArchR::paletteDiscrete(values = unique(msisensor_df$Patient),set = "stallion", reverse = TRUE)

png(paste0(res_path,"/msisensor.png"), units = "in", res = 300, width = 12, height = 18)
ggplot(msisensor_df, aes(x=sample_name, y=pert, fill=Patient)) + 
  geom_bar(stat="identity") +
  facet_wrap(~Patient, scales="free_x")+
  theme_minimal() +
  scale_fill_manual(values = msi_colors) +
  theme(axis.text.x=element_text(angle=90, size = 8))
dev.off()
```

