---
title: "ascat"
output: html_document
date: "2023-06-27"
---
```{r}
library(ASCAT)
```

```{r}
getwd()
ascat.bc = ascat.loadData(Tumor_LogR_file = "results_wes_full_40samples/variant_calling/ascat/113B_CM+_vs_113B_PBMC/113B_CM+_vs_113B_PBMC.tumour_tumourLogR.txt", Tumor_BAF_file = "results_wes_full_40samples/variant_calling/ascat/113B_CM+_vs_113B_PBMC/113B_CM+_vs_113B_PBMC.tumour_tumourBAF.txt", Germline_LogR_file = "results_wes_full_40samples/variant_calling/ascat/113B_CM+_vs_113B_PBMC/113B_CM+_vs_113B_PBMC.tumour_normalLogR.txt", Germline_BAF_file = "results_wes_full_40samples/variant_calling/ascat/113B_CM+_vs_113B_PBMC/113B_CM+_vs_113B_PBMC.tumour_normalBAF.txt", genomeVersion = "hg38") # isTargetedSeq=T for targeted sequencing data


ascat.plotRawData(ascat.bc, img.prefix = "Before_correction_")
ascat.bc = ascat.correctLogR(ascat.bc, GCcontentfile = "GC_example.txt", replictimingfile = "RT_example.txt")
ascat.plotRawData(ascat.bc, img.prefix = "After_correction_")
ascat.bc = ascat.aspcf(ascat.bc) # penalty=25 for targeted sequencing data
ascat.plotSegmentedData(ascat.bc)
ascat.output = ascat.runAscat(ascat.bc, write_segments = T) # gamma=1 for HTS data
QC = ascat.metrics(ascat.bc,ascat.output)
save(ascat.bc, ascat.output, QC, file = 'ASCAT_objects.Rdata')
```


```{r}

```


